events {}

http {

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    upstream user_service {
        server user-service:8001;
    }

    upstream order_service {
        server order-service:8002;
    }

    upstream payment_service {
        server payment-service:8003;
    }

    server {
        listen 8080;

        location /users {
            proxy_pass http://user_service;
        }

        location /orders {
            proxy_pass http://order_service;
        }

        location /payments {
            proxy_pass http://payment_service;
        }

        location /health {
            return 200 "API Gateway is healthy\n";
        }
    }
}
