http_port 3128

acl localnet src 172.18.0.0/16
http_access allow localnet
http_access deny all

access_log stdio:/var/log/squid/access.log
cache_log /var/log/squid/cache.log

http_access allow localnet
http_access deny all
